import { useState } from 'react'
import useMobileLayout from '../../hooks/useMobileLayout.js'
import TransactionList from '../../components/transactions/TransactionList.jsx'
import PositionCard from '../../components/positions/PositionCard.jsx'
import { positions, findMarket, money, transactions } from '../../demo/fixtures.js'
import { useDemo } from '../../demo/useDemo.js'
import { PageHeading, Panel, Metric, Tabs, Link, DemoNote, Badge, Empty, Button } from '../../components/ui/primitives.jsx'
import StatePanel, { ScenarioControl } from '../../components/feedback/StatePanel.jsx'
export function TransactionTable({ items }) { return <TransactionList items={items} /> }
export default function PortfolioView({ route, params }) {
  const mobile = useMobileLayout()
  const demo = useDemo()
  const [query, setQuery] = useState('')
  const [scenario, setScenario] = useState('')
  const [filter, setFilter] = useState('All outcomes')
  const allTransactions = [...transactions, ...demo.demoTransactions]
  const item = positions.find(p => p.id === params.positionId)
  const tabs = [['Overview',''],['Open positions','/open'],['Resolved','/resolved'],['Claimable','/claimable'],['Activity','/activity']]
  let filtered = positions.filter(p => findMarket(p.marketId).question.toLowerCase().includes(query.toLowerCase()) && (filter==='All outcomes' || p.outcome===filter))
  if (route.path.endsWith('/open')) filtered = filtered.filter(p => p.status==='Open')
  if (route.path.endsWith('/resolved') || route.path.endsWith('/claimable')) filtered = filtered.filter(p => p.status!=='Open')
  const content = params.positionId ? !item ? <Empty title="Position not found" /> : <div className="two-columns"><Panel title="Position overview" className="padded"><h2>{findMarket(item.marketId).question}</h2><Badge tone={item.outcome==='YES'?'positive':'danger'}>{item.outcome}</Badge><div className="detail-rows"><div><span>Shares</span><strong>{item.shares}</strong></div><div><span>Illustrative entry cost</span><strong>{money(item.shares*item.entry/100)}</strong></div><div><span>Current quoted value (estimate)</span><strong>{money(item.shares*(item.outcome==='YES'?findMarket(item.marketId).yes:100-findMarket(item.marketId).yes)/100)}</strong></div><div><span>Lifecycle</span><Badge>{item.status}</Badge></div><div><span>Result</span><strong>{findMarket(item.marketId).result || 'Unresolved'}</strong></div><div><span>Claim status</span><strong>{item.status==='Claimable' ? demo.claims['demo-claim-1'] || 'Eligible · not paid' : 'Not available'}</strong></div></div><Link href={`/markets/${item.marketId}`} className="button secondary">Open associated market</Link></Panel><Panel title="Transaction history" className="padded"><TransactionTable items={allTransactions.filter(t=>t.id===item.reference)} /><p className="muted">Demo references are not transaction signatures.</p>{item.status==='Claimable' && <Link href="/claims/demo-claim-1" className="button primary">Review demo claim</Link>}</Panel></div> : route.path.endsWith('/activity') ? <TransactionTable items={allTransactions} /> : <><div className="discovery-toolbar"><input aria-label="Search positions" placeholder="Search positions…" value={query} onChange={e=>setQuery(e.target.value)} /><select aria-label="Filter outcomes" value={filter} onChange={e=>setFilter(e.target.value)}>{['All outcomes','YES','NO'].map(x=><option key={x}>{x}</option>)}</select></div>{!filtered.length?<Empty title="No matching positions" />:mobile?<div className="position-cards">{filtered.map(p=><PositionCard key={p.id} position={p} />)}</div>:<div className="table-scroll"><table><thead><tr><th>Market / position</th><th>Outcome</th><th>Shares</th><th>Entry cost</th><th>Current estimate</th><th>Status</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><Link href={`/positions/${p.id}`}>{findMarket(p.marketId).question}</Link></td><td><Badge tone={p.outcome==='YES'?'positive':'danger'}>{p.outcome}</Badge></td><td>{p.shares}</td><td>{money(p.shares*p.entry/100)}</td><td>{money(p.shares*(p.outcome==='YES'?findMarket(p.marketId).yes:100-findMarket(p.marketId).yes)/100)}</td><td><Badge>{p.status}</Badge></td></tr>)}</tbody></table></div>}</>
  return <><PageHeading title={params.positionId?'Position details':'Your portfolio'} description="A clear view of your positions, from prediction to resolution." actions={<Link href="/transactions" className="button secondary">Transaction history</Link>} /><DemoNote>All positions are fixtures. Values are estimates, not realized returns.</DemoNote><div className="metrics-grid"><Metric label="Illustrative position value" value="$181.20" detail="Marked to fixture prices · estimate" /><Metric label="Open positions" value="2" detail="Unresolved demonstration markets" /><Metric label="Available demo claim" value="$80.00" detail="Eligible does not mean paid" /><Metric label="Realized returns" value="Unavailable" detail="No realized-return ledger connected" /></div>{!params.positionId && <Tabs items={tabs.map(([label,suffix])=>({label,href:'/portfolio'+suffix}))} active={route.path} />}<ScenarioControl feature="portfolio" value={scenario} onChange={setScenario} />{scenario?<><StatePanel id={scenario} onAction={()=>setScenario('')} />{demo.wallet && /loading|partial|stale|synchronization/i.test(scenario) && <div className="refresh-preserved-content">{content}</div>}</>:!demo.wallet?<Panel className="padded"><h2>Explore with a demo wallet</h2><p>These positions are fictional. Enable the local demo account to view them.</p><Button variant="primary" onClick={()=>demo.setWallet(true)}>Use demo wallet</Button></Panel>:content}</>
}
