import {useState} from 'react'
import {Field,Button} from '../../components/ui/primitives.jsx'
import {api} from '../../services/api.js'
import TransactionFlow from './TransactionFlow.jsx'
export default function CreationApproval({draft,update}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false)
 const seconds=value=>value?Math.floor(Date.parse(value+'Z')/1000):0
 async function upload(file){if(!file)return;setBusy(true);setError('');try{if(!file.type.startsWith('image/')||file.size>10*1024*1024)throw Error('Choose an image smaller than 10 MB.');const ticket=await api('/panta/image-upload',{method:'POST',body:{}});const target=new URL(ticket.uploadUrl);if(target.protocol!=='https:'||target.hostname!=='api.cloudinary.com')throw Error('Unsupported upload destination.');if(Date.parse(ticket.expiresAt)<=Date.now())throw Error('Upload permission expired. Retry.');const form=new FormData();for(const [key,value]of Object.entries(ticket.fields))form.append(key,String(value));form.append('file',file);const response=await fetch(ticket.uploadUrl,{method:'POST',body:form,signal:AbortSignal.timeout(60000)});const data=await response.json();if(!response.ok||!data.secure_url)throw Error('Image upload failed.');update('imageUrl',data.secure_url)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const input={question:draft.question,resolutionRule:draft.criteria,sourcesOfTruth:[draft.source],category:draft.category,startTime:seconds(draft.startTime),endTime:seconds(draft.deadline),resolutionTime:seconds(draft.resolutionTime),imageUrl:draft.imageUrl||'',description:draft.description,marketType:draft.marketType||'standard',eventInProgress:!!draft.eventInProgress}
 return <div className="stack"><Field label="Public market image URL"><input type="url" value={draft.imageUrl||''} onChange={e=>update('imageUrl',e.target.value)}/></Field><Field label="Or upload a market image (recommended 1024 × 1024)"><input type="file" accept="image/*" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></Field>{busy&&<p>Uploading image...</p>}{error&&<p role="alert">{error}</p>}<Field label="Start time (UTC)"><input type="datetime-local" value={draft.startTime||''} onChange={e=>update('startTime',e.target.value)}/></Field><Field label="Resolution time (UTC)"><input type="datetime-local" value={draft.resolutionTime||''} onChange={e=>update('resolutionTime',e.target.value)}/></Field><Field label="Market type"><select value={draft.marketType||'standard'} onChange={e=>update('marketType',e.target.value)}><option value="standard">Standard</option><option value="breaking">Breaking event</option></select></Field>{draft.marketType==='breaking'&&<label><input type="checkbox" checked={!!draft.eventInProgress} onChange={e=>update('eventInProgress',e.target.checked)}/> Event is already in progress</label>}<p>Start must precede closing time, and resolution cannot precede closing. Panta validates the current on-chain minimum start delay.</p><TransactionFlow kind="create" input={input} disabled={busy||!input.startTime||!input.endTime||!input.resolutionTime||!input.imageUrl}/><Button onClick={()=>setError('Quotes use the current on-chain creation fee; no guessed fee is displayed.')}>About creation fees</Button></div>
}
