import {useEffect,useRef,useState} from 'react'
import {Buffer} from 'buffer'
import {useWallet} from '../../hooks/useWallet.js'
import {useAuth} from '../auth/useAuth.js'
import {api} from '../../services/api.js'
import {Button,Badge,Link,Panel} from '../../components/ui/primitives.jsx'
import WalletPanel from '../wallet/WalletPanel.jsx'
import {formatBase} from './units.js'
export function Receipt({intent,onCheck,busy}){return <div className="stack"><Badge>{intent.state.replaceAll('_',' ')}</Badge><p>Chain: {intent.chainStatus.replaceAll('_',' ')} · Panta registration/reporting: {intent.providerStatus.replaceAll('_',' ')}</p>{intent.signature&&<p className="mono" style={{overflowWrap:'anywhere'}}>Signature: {intent.signature}</p>}{intent.error&&<p role="alert">{intent.error}</p>}{intent.chainStatus==='confirmed'&&<p>Confirmed on chain. Positions may still be synchronizing with Panta.</p>}{intent.signature&&<Button disabled={busy} onClick={onCheck}>Check status / retry reporting</Button>}{intent.kind==='create'&&intent.providerStatus==='registered'&&<Link href={'/markets/'+intent.quote.expectedEventPda}>Open confirmed market</Link>}<Link href={'/transactions/'+intent.id}>Open recovery record</Link></div>}
export default function TransactionFlow(props){const wallet=useWallet(),auth=useAuth();return <BoundTransactionFlow key={JSON.stringify([props.kind,props.input,wallet.address,auth.session?.id])} {...props}/>}
function BoundTransactionFlow({kind,input,disabled=false}){
 const wallet=useWallet(),auth=useAuth();const [intent,setIntent]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[state,setState]=useState('reviewing'),[now,setNow]=useState(()=>Date.now())
 const lock=useRef(false),epoch=useRef(0),request=useRef(null),scope=JSON.stringify([kind,input,wallet.address,auth.session?.id])
 useEffect(()=>()=>{epoch.current++},[])
 useEffect(()=>{if(!intent?.quote?.expiresAt)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[intent?.quote?.expiresAt])
 const expired=!!intent?.quote?.expiresAt&&Date.parse(intent.quote.expiresAt)<=now
 async function run(action){if(lock.current)return;lock.current=true;setBusy(true);setError('');const current=epoch.current;try{await action(current)}catch(e){if(current===epoch.current){const rejected=e.code===4001||e.code==='WALLET_REJECTED';setState(rejected?'signature_rejected':'failed');setError(rejected?'Wallet approval rejected. No transaction was submitted.':e.message)}}finally{lock.current=false;setBusy(false)}}
 const quote=()=>run(async current=>{setState('quote_loading');request.current||=crypto.randomUUID();const value=await api('/panta/intents',{method:'POST',body:{kind,input:{...input,wallet:wallet.address},requestId:request.current}});if(current!==epoch.current)return;setIntent(value);setState(value.state)})
 const approve=()=>run(async current=>{setState('building');const built=await api('/panta/intents/'+intent.id+'/build',{method:'POST',body:{}});if(current!==epoch.current)return;setIntent(built);setState('awaiting_signature');const signed=await wallet.sign(Uint8Array.from(Buffer.from(built.approval.transaction,'base64')),built.approval.chain);if(current!==epoch.current)throw Error('Account or transaction details changed. Nothing was submitted.');setState('submitting');let result;try{result=await api('/panta/intents/'+intent.id+'/broadcast',{method:'POST',body:{transaction:Buffer.from(signed).toString('base64')}})}catch{if(current===epoch.current){setState('confirmation_unknown');setIntent({...built,state:'confirmation_unknown',submissionUncertain:true});setError('Submission response was lost. Open the recovery record and check status before another action.')}return}if(current!==epoch.current)return;setIntent(result);setState(result.state)})
 const reconcile=()=>run(async current=>{setState('reconciling');const value=await api('/panta/intents/'+intent.id+'/reconcile',{method:'POST',body:{}});if(current===epoch.current){setIntent(value);setState(value.state)}})
 useEffect(()=>{if(!intent?.signature||['confirmed','failed','expired'].includes(intent.chainStatus))return;let stopped=false,count=0,timer;const check=async()=>{if(stopped||count++>=6)return;try{const next=await api('/panta/intents/'+intent.id+'/reconcile',{method:'POST',body:{}});if(!stopped){setIntent(next);setState(next.state);if(['confirmed','failed','expired'].includes(next.chainStatus))return}}catch(e){if(!stopped)setError(e.message)}if(!stopped)timer=setTimeout(check,5000)};timer=setTimeout(check,3000);return()=>{stopped=true;clearTimeout(timer)}},[intent?.id,intent?.signature,intent?.chainStatus,scope])
 if(auth.status!=='authenticated')return <Link className="button primary" href={'/auth?returnTo='+encodeURIComponent(location.pathname)}>Sign in to review this action</Link>
 if(!wallet.address)return <WalletPanel/>
 return <div className="stack"><Badge>Powered by Panta</Badge><p>{kind==='buy'?'Review your primary purchase':kind==='create'?'Review the creation fee':kind==='fees'?'Review creator fees':'Review your winning claim'}</p><small className="mono" style={{overflowWrap:'anywhere'}}>Wallet: {wallet.address}</small>{intent?.quote&&<Panel className="padded"><p>{kind==='create'?`Creation fee: ${formatBase(intent.quote.paymentUsdc)} USDC`:`Deposit: ${intent.quote.amountUsdc} USDC · Estimated shares: ${intent.quote.shares} · Protocol fee: ${intent.quote.feeUsdc} USDC`}</p>{kind==='create'&&<p>Liquidity: {formatBase(intent.quote.liquidityInjectionUsdc)} · Platform: {formatBase(intent.quote.platformRevenueUsdc)} USDC</p>}<p>{expired?'Quote expired':'Quote valid until '+new Date(intent.quote.expiresAt).toLocaleTimeString()}</p></Panel>}{intent?.build?.winningShares&&<p>Winning shares: {intent.build.winningShares}. Eligibility is checked again before approval.</p>}{intent?.build?.claimableFeesUsdc&&<p>Claimable creator fees: {formatBase(intent.build.claimableFeesUsdc)} USDC</p>}{intent?.review&&<p>Network fee: {intent.review.feeLamports} lamports · {intent.review.chain}</p>}<p role="status">{expired&&!intent?.signature?'quote expired':state.replaceAll('_',' ')}</p>{error&&<p role="alert">{error}</p>}{!intent?.signature&&!intent?.submissionUncertain&&<div className="button-row"><Button disabled={busy||disabled} onClick={()=>{if(intent){request.current=null;setIntent(null)}quote()}}>{intent?'Request new quote / eligibility':'Get quote / check eligibility'}</Button><Button variant="primary" disabled={busy||disabled||!intent||intent.state==='failed'||expired||!wallet.config?.ready} onClick={approve}>Review in wallet & approve</Button></div>}{!wallet.config?.ready&&<p>{wallet.config?.reason||wallet.configurationError}</p>}{intent&&<Receipt intent={intent} onCheck={reconcile} busy={busy}/>}<small>Network fees apply. A signature is not proof of confirmation.</small></div>
}
