import {z} from 'zod';
import {PublicKey} from '@solana/web3.js';
export const address=z.string().refine(v=>{try{return new PublicKey(v).toBytes().length===32}catch{return false}},'Invalid Solana address');
export const signature=z.string().regex(/^[1-9A-HJ-NP-Za-km-z]{64,88}$/);
export const decimal=z.string().regex(/^\d+(?:\.\d+)?$/).max(80);
export const units=z.string().regex(/^\d+$/).max(80);
export const amount=z.string().regex(/^(?:0|[1-9]\d*)(?:\.\d{1,6})?$/).max(24).refine(v=>BigInt(v.replace('.','').replace(/^0+/, '')||'0')>0);
export const phase=z.enum(['primary','secondary','resolved','cancelled']);
export const market=z.object({marketId:address,title:z.string(),category:z.string(),phase,description:z.string().optional(),yesPrice:decimal.nullish(),noPrice:decimal.nullish(),volumeUsdc:decimal.nullish(),endTime:z.number().nullish(),resolutionTime:z.number().nullish(),resolved:z.boolean().optional()}).passthrough();
export const trade=z.object({signature:z.string(),blockTime:z.number().nullish(),marketId:z.string().optional(),yesAmount:z.union([z.string(),z.number()]).optional(),noAmount:z.union([z.string(),z.number()]).optional()}).passthrough();
export const position=z.object({marketId:address,side:z.enum(['yes','no']),shares:decimal,phase,claimable:z.boolean(),claimed:z.boolean(),outcome:z.string().nullish()}).passthrough();
export const instruction=z.object({programId:address,data:z.string().max(20000),accounts:z.array(z.object({pubkey:address,isSigner:z.boolean(),isWritable:z.boolean()})).max(100)});
const built={recentBlockhash:address,lastValidBlockHeight:z.number().int().positive().optional(),expiresAt:z.string().optional(),derived:z.record(z.string(),z.string()).optional()};
const session=z.string().min(1).max(200);
const expiry=z.string().refine(v=>Number.isFinite(Date.parse(v)),'Invalid expiry');
export const account=z.object({userId:z.string(),name:z.string(),status:z.string(),canCreateMarkets:z.boolean()}).passthrough();
export const createInput=z.object({wallet:address,question:z.string().min(3).max(512),resolutionRule:z.string().min(1).max(2048),sourcesOfTruth:z.array(z.string().url().max(2048)).min(1).max(20),category:z.enum(['sports','crypto','politics','entertainment','finance','science','world','other']),startTime:z.number().int().positive(),endTime:z.number().int().positive(),resolutionTime:z.number().int().positive(),imageUrl:z.string().url().max(2048),marketType:z.enum(['standard','breaking']).default('standard'),eventInProgress:z.boolean().default(false),title:z.string().max(512).optional(),description:z.string().max(4000).optional(),region:z.string().max(128).optional()}).strict().refine(v=>v.startTime<v.endTime&&v.endTime<=v.resolutionTime,'Invalid market times').refine(v=>!v.eventInProgress||v.marketType==='breaking','In-progress requires a breaking market');
export const createQuote=z.object({createId:session,expectedEventPda:address,paymentUsdc:units,liquidityInjectionUsdc:units.optional(),platformRevenueUsdc:units.optional(),expiresAt:expiry}).passthrough();
export const buyInput=z.object({wallet:address,marketId:address,side:z.enum(['yes','no']),amountUsdc:amount,maxSlippageBps:z.number().int().min(0).max(5000).default(100)}).strict();
export const buyQuote=z.object({quoteId:session,marketId:address,side:z.enum(['yes','no']),amountUsdc:decimal,shares:decimal,avgPrice:decimal,feeUsdc:decimal,expiresAt:expiry}).passthrough();
export const createBuild=z.object({...built,createId:session,expectedEventPda:address,transaction:z.string().min(1).max(20000),paymentUsdc:units,buildFingerprint:z.string()}).passthrough();
export const buyBuild=z.object({...built,orderId:session,quoteId:session,wallet:address,marketId:address,side:z.enum(['yes','no']),amountUsdc:decimal,expectedShares:decimal,feeUsdc:decimal,instructions:z.array(instruction).min(1).max(30)}).passthrough();
export const claimBuild=z.object({...built,wallet:address,marketId:address,outcome:z.string(),winningShares:decimal,instructions:z.array(instruction).min(1).max(30)}).passthrough();
export const feesBuild=z.object({...built,wallet:address,marketId:address,claimableFeesUsdc:units,instructions:z.array(instruction).min(1).max(30)}).passthrough();
export type Market=z.infer<typeof market>;
export type BuyInput=z.infer<typeof buyInput>;
export type CreateInput=z.infer<typeof createInput>;
export type Build=z.infer<typeof createBuild>|z.infer<typeof buyBuild>|z.infer<typeof claimBuild>|z.infer<typeof feesBuild>;
export const listQuery=z.object({cursor:z.string().max(200).optional(),category:z.string().regex(/^[a-z]+$/).max(32).optional(),status:phase.optional(),createdBy:z.literal('me').optional(),limit:z.coerce.number().int().min(1).max(50).default(20)}).strict();
export function baseUnits(value:string,decimals=6):bigint {if(!/^\d+(?:\.\d+)?$/.test(value))throw Error('Invalid decimal amount');const [whole='',fraction='']=value.split('.');if(fraction.length>decimals)throw Error('Too many decimal places');return BigInt(whole)*10n**BigInt(decimals)+BigInt(fraction.padEnd(decimals,'0')||'0')}
