import FinancialWorkspace from '../features/panta/FinancialWorkspace.jsx'
import CreationApproval from '../features/panta/CreationApproval.jsx'
import WalletPanel from '../features/wallet/WalletPanel.jsx'
import useLiveQuery from '../hooks/useLiveQuery.js'
import {useEffect,useState} from 'react'
import {useDemo} from '../demo/useDemo.js'
import {useCommunity} from '../features/community/useCommunity.js'
import {permissions} from '../features/community/permissions.js'
import {PageHeading,Panel,Tabs,Link,Button,Field,Badge,Empty} from '../components/ui/primitives.jsx'
import {api} from '../services/api.js'
import {navigate} from './navigation.js'
import useUnsavedChanges from '../hooks/useUnsavedChanges.js'
export default function FeatureWorkspace({route,params}){
 if(route.feature==='creation')return <CreationWorkspace route={route} params={params}/>
 if(route.feature==='moderation')return <ModerationWorkspace route={route}/>
 return <FinancialWorkspace route={route} params={params}/>
}
const initialDraft={question:'',description:'',category:'science',deadline:'',criteria:'',source:''}
function CreationWorkspace({route,params}){
 const categories=useLiveQuery('/categories',60000)
 const [draft,setDraft]=useState(initialDraft),[drafts,setDrafts]=useState([]),[step,setStep]=useState(0),[dirty,setDirty]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState('')
 useUnsavedChanges(dirty)
 useEffect(()=>{let active=true;api('/market-drafts').then(items=>{if(!active)return;setDrafts(items);if(params.draftId){const item=items.find(d=>d.id===params.draftId);if(item)setDraft(item);else setError('Draft not found.')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[params.draftId])
 const steps=['Your question','Title & description','Category & deadline','Resolution rules','Market preview','Creation fee & approval']
 const update=(key,value)=>{setDraft({...draft,[key]:value});setDirty(true)}
 async function save(){setPending(true);try{const result=await api('/market-drafts',{method:'POST',body:draft});setDraft(result);setDirty(false);setError('Draft saved to your account.')}catch(e){setError(e.message)}finally{setPending(false)}}
 if(route.path==='/create/drafts')return <><PageHeading title="Your market drafts" actions={<Link className="button primary" href="/create">New draft</Link>}/>{error&&<p role="alert">{error}</p>}<div className="stack">{drafts.map(d=><Panel className="padded" title={d.question} key={d.id}><p>{d.description}</p><Link href={'/create/drafts/'+d.id}>Resume draft</Link></Panel>)}{!drafts.length&&!error&&<Empty title="No market drafts yet"/>}</div></>
 return <><PageHeading title="Turn a question into a clear market" description="Build a precise draft before reviewing fees and wallet approval." actions={<Link href="/create/drafts" className="button secondary">Your drafts</Link>}/><div className="wizard-progress">{steps.map((label,index)=><Button key={label} disabled={pending} aria-current={step===index?'step':undefined} onClick={()=>setStep(index)}>{index+1}. {label}</Button>)}</div><div className="wizard-grid"><Panel className="padded" title={steps[step]}><div className="restored-form">{step===0&&<><Field label="Your question"><textarea maxLength={160} value={draft.question} onChange={e=>update('question',e.target.value)} placeholder="Will a clearly defined event happen by a specific date?"/></Field><Link href="/ai">Explore the question with Signal AI</Link></>}{step===1&&<><Field label="Market title"><input maxLength={160} value={draft.question} onChange={e=>update('question',e.target.value)}/></Field><Field label="Description"><textarea maxLength={4000} value={draft.description} onChange={e=>update('description',e.target.value)}/></Field><Badge>Binary outcomes: YES / NO</Badge></>}{step===2&&<><Field label="Category"><select value={draft.category} onChange={e=>update('category',e.target.value)}>{(categories.data?.categories||[]).map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Deadline (UTC)"><input type="datetime-local" value={draft.deadline} onChange={e=>update('deadline',e.target.value)}/></Field></>}{step===3&&<><Field label="Resolution source"><input type="url" maxLength={2048} value={draft.source} onChange={e=>update('source',e.target.value)}/></Field><Field label="Resolution criteria"><textarea maxLength={2048} value={draft.criteria} onChange={e=>update('criteria',e.target.value)}/></Field></>}{step===4&&<><h3>{draft.question||'Untitled question'}</h3><p>{draft.description||'Add a description.'}</p><p>{draft.criteria||'Add resolution criteria.'}</p><p>Deadline: {draft.deadline||'Not selected'} UTC</p></>}{step===5&&<CreationApproval draft={draft} update={update}/>}{error&&<p role="status">{error}</p>}<div className="wizard-actions button-row"><Button disabled={step===0||pending} onClick={()=>setStep(step-1)}>Back</Button><Button disabled={pending||draft.question.trim().length<3} onClick={save}>{pending?'Saving...':'Save draft'}</Button><Button variant="primary" disabled={step===steps.length-1||pending} onClick={()=>setStep(step+1)}>Continue</Button></div></div></Panel><Panel className="padded preview-card" title="Market preview"><Badge>{draft.category}</Badge><h3>{draft.question||'Your question appears here'}</h3><p>{draft.description||'A clear description helps people evaluate the question.'}</p><div className="outcome-prices"><span className="yes-price">YES</span><span className="no-price">NO</span></div><small>Draft preview — no market has been published.</small></Panel></div></>
}
function ModerationWorkspace({route}){const c=useCommunity(),rooms=c.state.communities.filter(r=>permissions(c.state,r,c.actor,c.authenticated).manage);return <><PageHeading title="Community moderation" description="Review the communities you are authorized to manage."/><Tabs active={route.path} items={[['Overview','/moderation'],['Reports','/moderation/reports'],['Rooms','/moderation/rooms'],['Members','/moderation/users'],['Activity','/moderation/activity']].map(([label,href])=>({label,href}))}/><div className="stack">{rooms.map(room=><Panel className="padded" title={room.name} key={room.slug}><div className="button-row"><Link className="button secondary" href={'/rooms/'+room.slug+'/manage/reports'}>Reports</Link><Link className="button secondary" href={'/rooms/'+room.slug+'/manage/members'}>Members</Link><Link className="button secondary" href={'/rooms/'+room.slug+'/manage/activity'}>Activity</Link></div></Panel>)}{!rooms.length&&<Empty title="No communities to moderate" description="Only owners and moderators can access moderation tools."/>}</div></>}
export function OnboardingWorkspace({route}){const demo=useDemo();return <><PageHeading title={route.path.endsWith('/complete')?'Your workspace is ready':'Make room for your perspective'} description="Complete your profile and find your first community."/><Tabs active={route.path} items={[['Welcome','/onboarding'],['Profile','/onboarding/profile'],['Interests','/onboarding/interests'],['Wallet','/onboarding/wallet'],['Complete','/onboarding/complete']].map(([label,href])=>({label,href}))}/><Panel className="padded" title={'Welcome, '+demo.settings.name}><p>{route.path.endsWith('/wallet')?'Connect a wallet separately from your application account. Each transaction needs your explicit approval.':'Your account is ready. Add a biography and join communities that interest you.'}</p>{route.path.endsWith('/wallet')&&<WalletPanel/>}<div className="button-row"><Link className="button secondary" href="/settings/profile">Edit profile</Link><Link className="button primary" href="/rooms">Explore communities</Link><Button onClick={()=>navigate('/onboarding/complete')}>Finish setup</Button></div></Panel></>}
