import {useState} from 'react'
import {useAuth} from './useAuth.js'
import {api} from '../../services/api.js'
import {navigate} from '../../app/navigation.js'
import {safeReturnPath} from './config.js'
import {Button,Field,Link,PageHeading,Badge} from '../../components/ui/primitives.jsx'
export default function LiveAuthView({route}){
  const auth=useAuth(),[register,setRegister]=useState(location.pathname==='/auth/signup'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('')
  const submit=async e=>{e.preventDefault();if(pending)return;setPending(true);setError('');try{await api('/auth/'+(register?'register':'login'),{method:'POST',body:{name,email,password}});await auth.refresh();navigate(safeReturnPath(new URLSearchParams(location.search).get('returnTo')||'/rooms'))}catch(e){setError(e.message)}finally{setPending(false)}}
  const path=route?.path||location.pathname
  if(path==='/auth')return <><div className="auth-heading"><Badge tone="purple">WELCOME TO PANTA SIGNAL</Badge><h1>Welcome to your next perspective.</h1><p>Explore freely. Sign in to join the conversation and save your work.</p></div><div className="auth-methods"><Link className="auth-method" href="/auth/login"><span>@</span><span><strong>Email and password</strong><small>Sign in securely to your account</small></span><span>?</span></Link><Link className="auth-method" href="/auth/wallet"><span>?</span><span><strong>Wallet</strong><small>Connection not available yet</small></span><span>?</span></Link></div><div className="auth-link-row"><Link href="/auth/signup">Create an account</Link><Link href="/rooms">Explore communities</Link></div></>
  if(!['/auth/login','/auth/signup'].includes(path))return <><div className="auth-heading"><Badge tone="purple">ACCOUNT ACCESS</Badge><h1>{path==='/auth/wallet'?'Connect your wallet':route?.name||'Account verification'}</h1><p>{path.includes('session-expired')?'Your session has ended. Sign in again to continue.':path==='/auth/wallet'?'Wallet connection and ownership verification are not implemented yet. Email sign-in is available.':'This verification or recovery service is not connected yet. No email, code or reset link has been sent.'}</p></div>{path==='/auth/wallet'&&<div className="auth-methods"><Button disabled className="auth-method">Wallet connection unavailable</Button><p className="auth-caption">Connection, ownership verification and transaction approval are separate steps.</p></div>}<Link className="button primary full-width" href="/auth/login">Sign in with email</Link><Link className="button secondary full-width" href="/auth">Other sign-in methods</Link></>
  return <><PageHeading title={register?'Create your account':'Sign in to Panta Signal'} description="Your communities and account data are saved on the server."/><form className="restored-form" onSubmit={submit}>{register&&<Field label="Display name"><input autoComplete="name" minLength={2} maxLength={70} required value={name} onChange={e=>setName(e.target.value)}/></Field>}<Field label="Email"><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Password" hint="Use 12–128 characters."><input type="password" autoComplete={register?'new-password':'current-password'} minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></Field>{error&&<p className="field-error" role="alert">{error}</p>}<Button className="full-width" type="submit" variant="primary" disabled={pending}>{pending?'Please wait…':register?'Create account':'Sign in'}</Button><Button className="full-width" disabled={pending} onClick={()=>{setRegister(!register);setError('')}}>{register?'I already have an account':'Create an account'}</Button></form><div className="auth-link-row"><Link href="/auth/forgot-password">Forgot password?</Link><Link href="/auth">Other methods</Link></div><p className="muted">Email ownership verification, password recovery, social login and wallet verification are not configured yet.</p><Link href="/rooms">Browse communities</Link></>
}
