const labels=['Loading community','Loading feed','Empty community directory','No search results','No posts','No comments','No members','No pending requests','No reports','No banned members','Community not found','Community archived','Private community','Membership required','Join pending','Login required','Posting disabled','Approval required','Temporarily muted','Posting restricted','Banned','Post pending approval','Post rejected','Post removed','Post deleted','Comments locked','Attachment upload failed','Offline','Stale feed','Rate limited','Recoverable request error','Access denied','Action success','Membership rejected','Invite invalid or expired','Membership revoked','Like pending','Like failed','Comment posting','Comment validation error','Comment submission failed','Comment editing','Comment deleted','Comment removed','Restriction expired','Restriction action failed','Share copy failed','Share cancelled']
const descriptions={
"Loading community":"The community header and membership policy are loading. Wait for access to be checked before taking member actions.",
"Loading feed":"Posts are loading. Existing items and your current filters remain available while the feed refreshes.",
"Empty community directory":"No communities match this view yet. Explore all categories or create a room with a clear purpose and rules.",
"No search results":"No communities or posts match these filters. Clear the search or choose another category.",
"No posts":"There are no visible posts in this view. Approved members can start a conversation when posting is enabled.",
"No comments":"No visible comments yet. Add a question or source when this conversation permits replies.",
"No members":"There are no members matching this search. Clear the filters or review pending membership requests.",
"No pending requests":"All membership requests have been reviewed. New requests will appear here for authorized reviewers.",
"No reports":"There are no reports matching this queue. Reported content remains subject to the community rules.",
"No banned members":"No community bans match the current filters. Existing restrictions are listed separately.",
"Community not found":"This community address is unavailable. Check the link or choose a room from the directory.",
"Membership required":"Join this community before participating. Private communities require an approved membership request.",
"Join pending":"Your membership request awaits owner or moderator review. You can cancel it from the community header.",
"Login required":"Sign in to join, publish, save, or react. Public community content remains available to read.",
"Posting disabled":"Your current membership or the community posting policy does not allow new posts. Review the rules or membership status.",
"Approval required":"Member posts enter the review queue. Only approved posts appear in the public feed.",
"Post pending approval":"Your post is saved for review. You and authorized reviewers can see it; other members cannot yet.",
"Post rejected":"A reviewer declined this post. Review the moderation reason, edit your own draft, and resubmit when posting is permitted.",
"Attachment upload failed":"The image could not be prepared. Your text remains available; retry the image or remove it before publishing.",
"Offline":"A connected service is unavailable in this preview. Keep your local draft and retry when a real connection is restored.",
"Stale feed":"This preview represents an out-of-date feed. Preserve the current content and refresh before relying on membership or post status.",
"Rate limited":"Too many requests were attempted in this preview. Keep your draft and retry after the server-provided delay when integrated.",
"Recoverable request error":"The action did not complete. Your safe form inputs remain available so you can review and retry.",
"Access denied":"Your current community role cannot open these management tools. Return to the community or contact its owner.",
"Action success":"The local community action completed. Relevant membership, content, or review state now reflects the change.",
"Membership rejected":"Your request was declined. Review the community rules before submitting another request.",
"Invite invalid or expired":"This invitation cannot grant access. Request membership through the community page or obtain a new invitation.",
"Membership revoked":"Your membership was removed. Private posts and saved private content are unavailable until access is approved again.",
"Comment posting":"Your local comment is awaiting an explicit result. Duplicate submission is disabled while it is pending.",
"Comment validation error":"Write a non-empty comment of at most 2,000 characters. Your existing text remains editable.",
"Comment submission failed":"Your comment was not added. Its unsent text is preserved so you can retry without retyping.",
"Comment editing":"Edit your own comment while participation is permitted. Saving marks the contribution as edited.",
"Comment deleted":"The author deleted this comment. A placeholder retains the reply structure without counting as a visible comment.",
"Comment removed":"A moderator removed this comment. Replies remain accessible, and the removed text is hidden.",
"Restriction expired":"The temporary mute has ended. Posting and commenting follow the current community policies again.",
"Restriction action failed":"The membership change was not applied. Review the target role, reason, and your authority before retrying.",
"Share copy failed":"Clipboard access was unavailable. Select the canonical link and copy it manually; sharing does not grant private access.",
  'Private community':'Only approved members can view posts and member details. Request access; sharing a link never grants membership.',
  'Banned':'Participation and rejoining are disabled for this community until its ban is lifted. Public content remains readable. Earlier posts are not deleted.',
  'Posting restricted':'New posts are disabled. Comments remain allowed when the community permits comments. Review the restriction reason or request a review.',
  'Temporarily muted':'Posts and comments are disabled until the stated end time. An authorized moderator can change or lift this community restriction.',
  'Community archived':'This community is read-only. The owner can reopen it from management; existing public content remains available.',
  'Like failed':'The attempted like was not applied. Its previous count and pressed state have been restored; retry when ready.',
  'Like pending':'One local like update is pending. Duplicate submissions are disabled until you explicitly complete or fail the demo request.',
  'Share cancelled':'Sharing was cancelled. No message was sent and no share count was recorded. You can still copy the canonical link.',
  'Post removed':'A moderator removed this post from the community. Its content is hidden; a permitted moderator can restore it after review.',
  'Post deleted':'The author deleted this post. Its text and attachments are no longer shown. Return to the community feed.',
  'Comments locked':'This post remains readable, but new comments and replies are disabled. A moderator can unlock the conversation.',
}
export const communityStates=labels.map(name=>({id:'communityUX.'+name[0].toLowerCase()+name.slice(1).replace(/ ([a-z])/gi,(_,c)=>c.toUpperCase()),name,priority:'P0',group:'communityUX',description:descriptions[name]||`${name}. This deterministic community preview preserves available content and safe local drafts. Review your membership and retry or return to the community directory; no backend request is implied.`}))
