import { useAuth } from '../auth/useAuth.js'
import { useState } from 'react'
import { useDemo } from '../../demo/useDemo.js'
import { PageHeading, Panel, Tabs, Link, Button, Badge, DemoNote, Metric, Modal, Empty } from '../../components/ui/primitives.jsx'
import StatePanel, { ScenarioControl } from '../../components/feedback/StatePanel.jsx'
export default function ClaimsView({ route, params }) {
  const demo = useDemo()
  const auth = useAuth()
  const [scenario,setScenario]=useState('')
  const [open,setOpen]=useState(false)
  const state=demo.claims['demo-claim-1'] || 'eligible'
  const phases=['review','awaiting approval','submitting','pending','confirmed']
  const [phase,setPhase]=useState('review')
  function advance(){ if(!auth.requireWallet())return; const next=phases[phases.indexOf(phase)+1]; setPhase(next); if(next==='pending'||next==='confirmed') demo.setClaims(current=>({...current,'demo-claim-1':next})) }
  const visible=!(route.path.endsWith('/pending') && state!=='pending') && !(route.path.endsWith('/history') && state!=='confirmed') && !(route.path.endsWith('/available') && state!=='eligible')
  return <><PageHeading title="Your claims" description="Review resolution and eligibility before taking the next step." /><DemoNote>Claim flows are simulated. Eligibility is not a completed payout.</DemoNote><div className="metrics-grid three"><Metric label="Available (illustrative)" value={state==='eligible'?'$80.00':'$0.00'} detail="One fictional resolved position" /><Metric label="Pending demo claims" value={state==='pending'?'1':'0'} detail="Not confirmed" /><Metric label="Simulated completed" value={state==='confirmed'?'1':'0'} detail="No real funds paid" /></div><Tabs items={[['Overview',''],['Available','/available'],['Pending','/pending'],['History','/history']].map(([label,s])=>({label,href:'/claims'+s}))} active={route.path} /><ScenarioControl feature="claims" value={scenario} onChange={setScenario} />{scenario?<StatePanel id={scenario} onAction={()=>setScenario('')} />:params.claimId && params.claimId!=='demo-claim-1'?<Empty title="Claim not found" />:!visible?<Empty title="No claims in this view" description="Use the explicit simulated claim flow to move a claim through its stages." />:<Panel title="Demo network upgrade" subtitle="Resolved YES · illustrative claim" className="padded"><div className="claim-summary"><div><Badge tone={state==='confirmed'?'positive':'purple'}>{state==='eligible'?'Eligible · not paid':`Simulated ${state}`}</Badge><h3>80 YES shares</h3><p>Position demo-pos-3 · result from a fictional demonstration release log.</p><Link href="/positions/demo-pos-3">Review position and transaction history →</Link></div><div><strong className="large-number">$80.00</strong><small>Illustrative payout</small></div></div><div className="button-row"><Link href="/claims/demo-claim-1" className="button secondary">Claim details</Link><Button variant="primary" disabled={state==='confirmed'} onClick={()=>{setPhase(state==='pending'?'pending':'review');setOpen(true)}}>{state==='confirmed'?'Already simulated claimed':state==='pending'?'Review pending demo claim':'Review demo claim'}</Button></div></Panel>}<Modal open={open} onClose={()=>setOpen(false)} title="Review demo claim"><DemoNote>No wallet approval is actually requested.</DemoNote><h3>Claim 80 illustrative USD</h3><p>Resolved outcome: YES · Held outcome: YES · Shares: 80.</p><p>Illustrative network fee: $0.01. This amount is not deducted from any wallet.</p><Badge tone="purple">Simulated: {phase}</Badge>{phase==='confirmed'?<p>Simulation completed. No blockchain payout occurred.</p>:<div className="modal-actions"><Button onClick={()=>{setOpen(false);setScenario('claims.approvalRejected')}}>Simulate rejection</Button><Button variant="primary" onClick={advance}>{phase==='review'?'Continue to demo approval':phase==='awaiting approval'?'Simulate approval':phase==='submitting'?'Mark simulated pending':'Simulate confirmation'}</Button></div>}</Modal></>
}
